### ISSUE TITLE
Segfault on linux shortly after startup

### ISSUE THREAD

**Issue by ChristophHaag** [toji/chrome-webvr-issues#27]
This is with the latest available Chromium_WebVR_Linux_SDK_0.4.4.zip 12/30/14

I start it with `./chrome-wrapper --no-sandbox --user-data-dir=/tmp/chromevr --disable-gpu-vsync`

it starts, shows the window for a few seconds and without any interaction it segfaults with and without an active rift, with intel and radeonsi.
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555689cdf3 in SkRegion::~SkRegion() ()
(gdb) bt
#0  0x000055555689cdf3 in SkRegion::~SkRegion() ()
#1  0x0000555556cccc5d in cc::FilterOperation::~FilterOperation() ()
#2  0x0000555556ccd7a8 in cc::FilterOperations::~FilterOperations() ()
#3  0x0000555556cd104a in cc::RenderPassDrawQuad::~RenderPassDrawQuad() ()
#4  0x0000555556ccf38b in cc::ListContainer<cc::DrawQuad>::~ListContainer() ()
#5  0x0000555556ccff25 in cc::RenderPass::~RenderPass() ()
#6  0x0000555556d8a2c5 in cc::DirectRenderer::DrawFrame(cc::ScopedPtrVector<cc::RenderPass>*, float, gfx::Rect const&, gfx::Rect const&, bool) ()
#7  0x0000555556d131a2 in cc::LayerTreeHostImpl::DrawLayers(cc::LayerTreeHostImpl::FrameData*, base::TimeTicks) ()
#8  0x0000555556d2778c in cc::SingleThreadProxy::DoComposite(base::TimeTicks, cc::LayerTreeHostImpl::FrameData*) ()
#9  0x0000555556d27489 in cc::SingleThreadProxy::CompositeImmediately(base::TimeTicks) ()
#10 0x0000555556c9a251 in ui::Compositor::Draw() ()
#11 0x00005555565499ba in base::debug::TaskAnnotator::RunTask(char const*, char const*, base::PendingTask const&) ()
#12 0x0000555556508f02 in base::MessageLoop::RunTask(base::PendingTask const&) ()
#13 0x00005555565090b9 in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) ()
#14 0x000055555650949b in base::MessageLoop::DoWork() ()
#15 0x000055555653f219 in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ()
#16 0x000055555651a7c0 in base::RunLoop::Run() ()
#17 0x000055555622ff52 in ChromeBrowserMainParts::MainMessageLoopRun(int*) ()
#18 0x0000555558602ca4 in content::BrowserMainLoop::RunMainMessageLoopParts() ()
#19 0x000055555843cf6d in content::BrowserMainRunnerImpl::Run() ()
#20 0x000055555843cb43 in content::BrowserMain(content::MainFunctionParams const&) ()
#21 0x00005555564c0695 in content::ContentMainRunnerImpl::Run() ()
#22 0x00005555564bf2b0 in content::ContentMain(content::ContentMainParams const&) ()
#23 0x0000555555f58378 in ChromeMain ()
#24 0x00007ffff19c1800 in __libc_start_main () from /usr/lib/libc.so.6
#25 0x0000555555f5823b in _start ()
```

**Comment by toji** [comment]
Thanks for the report. Hoping to update the experimental builds on all platforms soon-ish (next couple of weeks?) so I'll take a look at this then.

**Comment by toji** [comment]
I've fixed this problem, but need to handle a couple more things before I can update the builds. Thanks for your patience, and thanks for the report!
